<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Development_ITUpTheme</name>
   <tag></tag>
   <elementGuidId>76a8f70b-a0b5-42d1-a1a8-c940de190f60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wt4_wtDay_Event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ITUpTheme_wt17$block$wtMainContent$wt7$wtProjectsList$ctl00$wtTimeSheet_TasksList$wtTasksList$ctl00$wtTimeSheet_DayEvents$wtDayEventsList$ctl00$wt4$wtDay_Event</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wt4_wtDay_Event</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wt4_wtDay_Event','ITUpTheme_wt17$block$wtMainContent$wt7$wtProjectsList$ctl00$wtTimeSheet_TasksList$wtTasksList$ctl00$wtTimeSheet_DayEvents$wtDayEventsList$ctl00$wt4$wtDay_Event','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wt4_wtDay_Event','ITUpTheme_wt17$block$wtMainContent$wt7$wtProjectsList$ctl00$wtTimeSheet_TasksList$wtTasksList$ctl00$wtTimeSheet_DayEvents$wtDayEventsList$ctl00$wt4$wtDay_Event','Change','__OSVSTATE,',0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wt4_wtDay_Event&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wt4_wtDay_Event']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wt4_wtDay_EventAjaxRfrsh']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Development'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestingProjectForTestingPurpose'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacation'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
   </webElementXpaths>
</WebElementEntity>
