<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HolidayVacationWeekend</name>
   <tag></tag>
   <elementGuidId>5c477c46-e227-4845-8219-dbf7a6f99d01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wtContainer_Day_Event_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wtContainer_Day_Event_2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DayEvent OSInline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HolidayVacationWeekend</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wtContainer_Day_Event_2&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList_ctl00_wtContainer_Day_Event_2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Development'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestingProjectForTestingPurpose'])[1]/following::div[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/div/div[3]/span/div</value>
   </webElementXpaths>
</WebElementEntity>
