<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>ff9d56a8-a144-4df4-8ce3-e98020476709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ListRecords</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HolidayVacationWeekendHolidayVacationWeekendHolidayVacationWeekendHolidayVacationWeekendHolidayVacationWeekendHolidayVacationWeekendHolidayVacationWeekend</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTimeSheet_DayEvents_wtDayEventsList']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ITUpTheme_wt17_block_wtMainContent_wt7_wtProjectsList_ctl00_wtTimeSheet_TasksList_wtTasksList_ctl00_wtTask_Container']/div[3]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Development'])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestingProjectForTestingPurpose'])[1]/following::span[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/div/div[3]/span</value>
   </webElementXpaths>
</WebElementEntity>
